name: dart validation

on:
  pull_request:

env:
  FLUTTER_VERSION: '3.29.3'

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter ${{env.FLUTTER_VERSION}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get
        working-directory: toxic_floor_sprayer_3000_pro

      - name: Dart Analyzer
        run: dart analyze --fatal-infos
        working-directory: toxic_floor_sprayer_3000_pro

